---
title: "Simple document"
output: github_document
---

I'm an R Markdown document! 

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(readxl)
library(haven)
```
## import data

I want to import 'FAS_litters.csv'.

```{r}
library(readr)
litters_df <- read_csv("data/FAS_litters.csv")
View(FAS_litters)
```

## want better names
```{r}
names(litters_df)

litters_df = janitor::clean_names(litters_df)
```

## look at dataset
```{r, evol = FALSE}
head(litters_df,20)
tail(litters_df,20)

view(litters_df)
```

```{r}
skimr::skim(litters_df)
```

```{r, evol = FALSE}
litters_df = 
  read_csv(
    "data/FAS_litters.csv",
    skip = 5,
    col_names = FALSE,
    na = "Low8")
```

## Parsing columns

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
```

## reading from excel

```{r}
mlb11_df = read_excel("data/mlb11.xlsx")
```

```{r}
fellow_df = read_excel("data/LotR_Words.xlsx", range = "B3:D6")
```

##read a SAS file
```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")

# Section 1

Here's a **code chunk** that samples from 
a _normal distribution_:

```{r}
samp = rnorm(100)
length(samp)
```

# Section 2

I can take the mean of the sample, too!
The mean is `r mean(samp)`.